### ISSUE TITLE
One of the parameters specified was missing or invalid: group_ids is undefined

### ISSUE THREAD

**Issue by KweezyCode** [vkbottle/vkbottle#1004]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

пытаюсь запустить бота на получение сообщений, но вылезает ошибка, в том числе из файлов с примерами

### Пример кода

```python3
from vk_token import vk_token
from vkbottle.bot import Bot, Message, MessageEvent
from vkbottle.dispatch.rules.base import FromUserRule


bot = Bot(vk_token)

@bot.on.message(FromUserRule())
async def handle_message(message: Message):
    for attachment in message.attachments:
        # Обработка вложений
        print(f"Обработано вложение: {attachment}")

bot.run_forever()
```

### Логи
```
INFO     | 2024-09-14 15:27:22,353 | vkbottle.framework.bot.bot:run_forever:84 > Loop will be run forever
DEBUG    | 2024-09-14 15:27:22,354 | asyncio.selector_events:__init__:54 > Using selector: EpollSelector
INFO     | 2024-09-14 15:27:22,357 | vkbottle.framework.bot.bot:run_polling:76 > Starting polling for <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
DEBUG    | 2024-09-14 15:27:22,359 | vkbottle.polling.bot_polling:get_server:52 > Getting polling server...
DEBUG    | 2024-09-14 15:27:22,361 | vkbottle.api.api:validate_request:113 > API request was validated
DEBUG    | 2024-09-14 15:27:23,204 | vkbottle.api.api:request:78 > Request groups.getById with {} data returned {"error":{"error_code":100,"error_msg":"One of the parameters specified was missing or invalid: group_ids is undefined","request_params":[{"key":"v","value":"5.199"},{"key":"method","value":"groups.getById"},{"key":"oauth","value":"1"}]}}
ERROR    | 2024-09-14 15:27:23,210 | vkbottle.tools.loop_wrapper:run:82 > One of the parameters specified was missing or invalid: group_ids is undefined
Traceback (most recent call last):
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/tools/loop_wrapper.py", line 80, in run
    task_result.result()
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/framework/bot/bot.py", line 78, in run_polling
    async for event in polling.listen():
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/polling/bot_polling.py", line 66, in listen
    server = await self.get_server()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/polling/bot_polling.py", line 54, in get_server
    self.group_id = (await self.api.request("groups.getById", {}))["response"]["groups"][
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/api/api.py", line 79, in request
    return await self.validate_response(method, data, response)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/api/api.py", line 104, in validate_response
    response = await validator.validate(method, data, response, self)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kweezy/Рабочий стол/Proj/lib/python3.11/site-packages/vkbottle/api/response_validator/vk_api_error_validator.py", line 48, in validate
    raise VKAPIError[code](**error)
vkbottle.exception_factory.base_exceptions.VKAPIError_100: One of the parameters specified was missing or invalid: group_ids is undefined
```

**Comment by luwqz1** [comment]
какая версия вкботл и типов?

**Comment by KweezyCode** [comment]
> какая версия вкботл и типов?

я изначально подумал, что это библиотека только для юзерботов. после импорта user всё заработало
