### ISSUE TITLE
ValidationError объекта опроса

### ISSUE THREAD

**Issue by AsDeep** [vkbottle/vkbottle#1016]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

При вызове метода через `ctx_api.polls` вылезает ошибка pydantic на поле "anonymous". Если делать запрос с теми же параметрами через `ctx_api.request`, никаких проблем не возникает.
Хендлер сообщений также поднимает `ValidationError` при обработке сообщения с прикрепленным опросом.

### Пример кода

```python3
@labeler.message(text=['/закреп'])
async def pin_handler(message: Message):
    if message.reply_message is not None:
        result = await message.ctx_api.polls.create(question='Закрепить это сообщение?', add_answers=json.dumps(["да", "нет"]))
        print(result.id)
```

### Логи

```
Traceback (most recent call last):

  File "C:\Users\trplk\PycharmProjects\YakkkBOT\testing\handlers\greetings.py", line 24, in pin_handler
    result = await message.ctx_api.polls.create(question=f'Закрепить это сообщение? ', add_answers=
                   │       └ <property object at 0x0000019FEF124C70>
                   └ MessageMin(conversation_message_id=2622, date=1727396856, from_id=123, id=896879, out=False, peer_id=2000000014, text='...

  File "C:\Users\trplk\PycharmProjects\YakkkBOT\venv\Lib\site-packages\vkbottle_types\codegen\methods\polls.py", line 75, in create
    return model(**response).response
           │       └ {'response': {'multiple': False, 'end_date': 0, 'closed': False, 'is_board': False, 'can_edit': True, 'can_vote': True, 'can_...
           └ <class 'vkbottle_types.codegen.responses.polls.PollsCreateResponse'>
  File "C:\Users\trplk\PycharmProjects\YakkkBOT\venv\Lib\site-packages\pydantic\main.py", line 341, in __init__
    raise validation_error
          └ ValidationError(model='PollsCreateResponse', errors=[{'loc': ('response', 'anonymous'), 'msg': 'value is not a valid dict', '...

pydantic.error_wrappers.ValidationError: 1 validation error for PollsCreateResponse
response -> anonymous
  value is not a valid dict (type=type_error.dict)

```

**Comment by luwqz1** [comment]
скинь полный респонс на пастбин в виде словаря

**Comment by AsDeep** [comment]
> скинь полный респонс на пастбин в виде словаря

https://pastebin.com/L5xKsZRd

**Comment by luwqz1** [comment]
> > скинь полный респонс на пастбин в виде словаря
> 
> https://pastebin.com/L5xKsZRd

хорошо, завтра исправлю
