### ISSUE TITLE
Error in BaseMessageMin.get_chat_members (IsAdminRule)

### ISSUE THREAD

**Issue by NousadS** [vkbottle/vkbottle#1085]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

Когда просто пытаюсь использовать _IsAdminRule_ из пакета _vkbottle.dispatch.rules.base_ **:|**

### Пример кода

```python3
import os

import dotenv
from vkbottle.bot import Bot, Message
from vkbottle.dispatch.rules.base import CommandRule, IsAdminRule

dotenv.load_dotenv()

bot = Bot(token=os.environ.get("TOKEN"))

bot.labeler.message_view.replace_mention = True


@bot.on.chat_message(CommandRule("очень_полезная_команда", ["!"], 0), IsAdminRule())
async def handler(message: Message, args: tuple):
    await message.answer("Очень полезный текст")


bot.run_forever()
```

### Логи

INFO     | 2024-12-10 20:20:13 | vkbottle.framework.bot.bot:run_forever:84 > Loop will be run forever
INFO     | 2024-12-10 20:20:13 | vkbottle.framework.bot.bot:run_polling:76 > Starting polling for <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
DEBUG    | 2024-12-10 20:20:13 | vkbottle.polling.bot_polling:get_server:59 > Getting polling server...
DEBUG    | 2024-12-10 20:20:13 | vkbottle.api.api:validate_request:113 > API request was validated
DEBUG    | 2024-12-10 20:20:14 | vkbottle.api.api:request:78 > Request groups.getById with {} data returned {"response":{"groups":[{"id":XXX,"name":"XXX","screen_name":"XXX","is_closed":2,"type":"group","photo_50":"XXX"}],"profiles":[]}}
DEBUG    | 2024-12-10 20:20:14 | vkbottle.api.api:validate_response:105 > API response was validated
DEBUG    | 2024-12-10 20:20:14 | vkbottle.api.api:validate_request:113 > API request was validated
DEBUG    | 2024-12-10 20:20:14 | vkbottle.api.api:request:78 > Request groups.getLongPollServer with {'group_id': XXX} data returned {"response":{"key":"XXX","server":"https:\/\/lp.vk.com\/whp\/XXX","ts":"31"}}
DEBUG    | 2024-12-10 20:20:14 | vkbottle.api.api:validate_response:105 > API response was validated
DEBUG    | 2024-12-10 20:20:14 | vkbottle.polling.bot_polling:listen:94 > Starting listening to Longpoll
DEBUG    | 2024-12-10 20:20:14 | vkbottle.polling.bot_polling:get_event:46 > Making long request to get event with longpoll...
DEBUG    | 2024-12-10 20:20:18 | vkbottle.framework.bot.bot:run_polling:79 > New event was received: {'ts': '32', 'updates': [{'group_id': XXX, 'type': 'message_new', 'event_id': 'XXX', 'v': '5.199', 'object': {'message': {'date': 1733858418, 'from_id': 541161804, 'id': 0, 'version': 10000407, 'out': 0, 'important': False, 'is_hidden': False, 'attachments': [], 'conversation_message_id': 157, 'fwd_messages': [], 'text': '!очень_полезная_команда', 'is_unavailable': True, 'peer_id': 2000000002, 'random_id': 0}, 'client_info': {'button_actions': ['text', 'vkpay', 'open_app', 'location', 'open_link', 'open_photo', 'callback', 'intent_subscribe', 'intent_unsubscribe'], 'keyboard': True, 'inline_keyboard': True, 'carousel': True, 'lang_id': 0}}}]}
DEBUG    | 2024-12-10 20:20:18 | vkbottle.polling.bot_polling:get_event:46 > Making long request to get event with longpoll...
DEBUG    | 2024-12-10 20:20:18 | vkbottle.dispatch.base:route:18 > Routing update {'group_id': XXX, 'type': 'message_new', 'event_id': 'bb668a4629833c7c4831ea297006612e0a78c41c', 'v': '5.199', 'object': {'message': {'date': 1733858418, 'from_id': 541161804, 'id': 0, 'version': 10000407, 'out': 0, 'important': False, 'is_hidden': False, 'attachments': [], 'conversation_message_id': 157, 'fwd_messages': [], 'text': '!очень_полезная_команда', 'is_unavailable': True, 'peer_id': 2000000002, 'random_id': 0}, 'client_info': {'button_actions': ['text', 'vkpay', 'open_app', 'location', 'open_link', 'open_photo', 'callback', 'intent_subscribe', 'intent_unsubscribe'], 'keyboard': True, 'inline_keyboard': True, 'carousel': True, 'lang_id': 0}}}
DEBUG    | 2024-12-10 20:20:18 | vkbottle.dispatch.views.abc.message:handle_event:46 > Handling event (message_new) with message view
DEBUG    | 2024-12-10 20:20:18 | vkbottle.dispatch.dispenser.abc:cast:27 > Casting state for peer_id 2000000002
ERROR    | 2024-12-10 20:20:18 | vkbottle.exception_factory.error_handler.error_handler:handle:48 > 'FieldInfo' object is not iterable
Traceback (most recent call last):

  File "/run/media/nousad/031342890D055036/wvc/bot/try.py", line 19, in <module>
    bot.run_forever()
    │   └ <function Bot.run_forever at 0x78d807d51260>
    └ <vkbottle.framework.bot.bot.Bot object at 0x78d80b170260>

  File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/framework/bot/bot.py", line 86, in run_forever
    self.loop_wrapper.run()
    │    │            └ <function LoopWrapper.run at 0x78d805c7b100>
    │    └ <vkbottle.tools.loop_wrapper.LoopWrapper object at 0x78d8089a8fb0>
    └ <vkbottle.framework.bot.bot.Bot object at 0x78d80b170260>
  File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/tools/loop_wrapper.py", line 78, in run
    tasks_results, _ = self.loop.run_until_complete(
                       │    │    └ <function BaseEventLoop.run_until_complete at 0x78d8071b77e0>
                       │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
                       └ <vkbottle.tools.loop_wrapper.LoopWrapper object at 0x78d8089a8fb0>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x78d8071b7740>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x78d8071b9580>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x78d8071559e0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x78d807d8e740>()>
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x78d807d8e740>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x78d807d8e740>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x78d807d8e740>()>
> File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/dispatch/base.py", line 24, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
          │    │            │      │        │    └ <vkbottle.dispatch.dispenser.builtin.BuiltinStateDispenser object at 0x78d807802300>
          │    │            │      │        └ <vkbottle.dispatch.base.Router object at 0x78d807d8cc20>
          │    │            │      └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
          │    │            └ {'group_id': XXX, 'type': 'message_new', 'event_id': 'XXX', 'v': '5.199', 'object'...
          │    └ <function ABCMessageView.handle_event at 0x78d805cb98a0>
          └ <BotMessageView handlers=[<FromFuncHandler handler blocking=True rules=(<PeerRule>, <CommandRule>, <IsAdminRule>)>] middlewar...
  File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/dispatch/views/abc/message.py", line 63, in handle_event
    result = await handler.filter(message)
                   │       │      └ MessageMin(conversation_message_id=157, date=1733858418, from_id=541161804, id=0, out=False, peer_id=2000000002, text='!очень...
                   │       └ <function FromFuncHandler.filter at 0x78d805c962a0>
                   └ <FromFuncHandler handler blocking=True rules=(<PeerRule>, <CommandRule>, <IsAdminRule>)>
  File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/dispatch/handlers/from_func_handler.py", line 20, in filter
    result = await rule.check(event)
                   │    │     └ MessageMin(conversation_message_id=157, date=1733858418, from_id=541161804, id=0, out=False, peer_id=2000000002, text='!очень...
                   │    └ <function IsAdminRule.check at 0x78d808c56ac0>
                   └ <IsAdminRule>
  File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/dispatch/rules/base.py", line 438, in check
    return event.peer_id != event.from_id and await event.user_is_admin(event.from_id)
           │     │          │     │                 │     │             │     └ 541161804
           │     │          │     │                 │     │             └ MessageMin(conversation_message_id=157, date=1733858418, from_id=541161804, id=0, out=False, peer_id=2000000002, text='!очень...
           │     │          │     │                 │     └ <function BaseMessageMin.user_is_admin at 0x78d805cbb100>
           │     │          │     │                 └ MessageMin(conversation_message_id=157, date=1733858418, from_id=541161804, id=0, out=False, peer_id=2000000002, text='!очень...
           │     │          │     └ 541161804
           │     │          └ MessageMin(conversation_message_id=157, date=1733858418, from_id=541161804, id=0, out=False, peer_id=2000000002, text='!очень...
           │     └ 2000000002
           └ MessageMin(conversation_message_id=157, date=1733858418, from_id=541161804, id=0, out=False, peer_id=2000000002, text='!очень...
  File "/run/media/nousad/031342890D055036/wvc/bot/.venv/lib/python3.12/site-packages/vkbottle/tools/mini_types/base/message.py", line 103, in user_is_admin
    return any(member.member_id == user_id and member.is_admin for member in members)
                                   │                                         └ FieldInfo(default=PydanticUndefined, default_factory=<class 'list'>, extra={})
                                   └ 541161804

TypeError: 'FieldInfo' object is not iterable
INFO     | 2024-12-10 20:20:22 | vkbottle.tools.loop_wrapper:run:88 > Caught keyboard interrupt. Shutting down...

**Comment by NousadS** [comment]
Упрощенный лог

```
ERROR    | 2024-12-10 20:37:52,888 | vkbottle.exception_factory.error_handler.error_handler:handle:48 > 'FieldInfo' object is not iterable
Traceback (most recent call last):
  File "/run/media/nousad/031342890D055036/wvc/try/.venv/lib/python3.12/site-packages/vkbottle/dispatch/base.py", line 24, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "/run/media/nousad/031342890D055036/wvc/try/.venv/lib/python3.12/site-packages/vkbottle/dispatch/views/abc/message.py", line 63, in handle_event
    result = await handler.filter(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/nousad/031342890D055036/wvc/try/.venv/lib/python3.12/site-packages/vkbottle/dispatch/handlers/from_func_handler.py", line 20, in filter
    result = await rule.check(event)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/nousad/031342890D055036/wvc/try/.venv/lib/python3.12/site-packages/vkbottle/dispatch/rules/base.py", line 438, in check
    return event.peer_id != event.from_id and await event.user_is_admin(event.from_id)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/nousad/031342890D055036/wvc/try/.venv/lib/python3.12/site-packages/vkbottle/tools/mini_types/base/message.py", line 103, in user_is_admin
    return any(member.member_id == user_id and member.is_admin for member in members)
                                                                             ^^^^^^^
TypeError: 'FieldInfo' object is not iterable
```
