### ISSUE TITLE
TypeError: 'coroutine' object is not callable

### ISSUE THREAD

**Issue by Doncode** [vkbottle/vkbottle#117]
**Опишите баг**
Вылетает исключение.
На предыдушей версии данной проблемы не наблюдалось 
database для хранения состояния не использую 

```
[VKBottle] While parent_processor was handling error occurred 
Traceback (most recent call last):
  File "/path/.venv/lib/python3.7/site-packages/vkbottle/framework/framework/swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "/path/.venv/lib/python3.7/site-packages/vkbottle/framework/bot/processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "/path/.venv/lib/python3.7/site-packages/vkbottle/framework/bot/processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "/path/vkbot.py", line 305, in branch4_handler
    await bot.branch.add(ans.peer_id, "branch5", offer_id=offer.id)
  File "/path/.venv/lib/python3.7/site-packages/vkbottle/framework/framework/branch/database_branch.py", line 99, in add
    await self.get_branch(branch, context).enter()
  File "/path/.venv/lib/python3.7/site-packages/vkbottle/framework/framework/branch/database_branch.py", line 36, in get_branch
    branch = bare()
TypeError: 'coroutine' object is not callable
 [TIME 22:05:53]
```

**Ваш код**
`await bot.branch.add(ans.peer_id, "branch5", offer_id=offer.id)`

**Заполните поля:**
vkbottle-2.7.5
Установлен c GIT

**Comment by Doncode** [comment]
Откатился на коммит 3ef038ddb169617cce8065b640d5d22dc59fb29b
Работает 
```bash
pip install git+https://github.com/timoniq/vkbottle.git@3ef038ddb169617cce8065b640d5d22dc59fb29b
```
