### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by LooPeKa** [vkbottle/vkbottle#119]
**Опишите баг**
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    bot = Bot("31fc73ccaafdabe479534eb645e1256ba6a59bcca734766ddbc1d86e57f0de3a741f6f63ad990593c9314")
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/vkbottle/framework/bot/bot.py", line 94, in __init__
    logger.add(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/loguru/_logger.py", line 935, in add
    handler = Handler(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/loguru/_handler.py", line 85, in __init__
    self._queue = multiprocessing.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Что должно было случится**
Ответит мне в сообщениях , выходит ошибка

**Ваш код**
https://pastebin.com/FuXm9JUd

**Заполните поля:**
 - OS: Android (PyDroid 3)
 - Version of vkbottle: 2.7.4 

**Дополнительная информация**
...

**Comment by markelovstyle** [comment]
`bot = Bot("token", mobile=True)`

**Comment by LooPeKa** [comment]
> `bot = Bot("token", mobile=True)`

Спасибо , святой!

**Comment by markelovstyle** [comment]
Не за что, закрывай issue.

**Comment by LooPeKa** [comment]
> `bot = Bot("token", mobile=True)`

)
