### ISSUE TITLE
Ошибка при работе росток (sprout)

### ISSUE THREAD

**Issue by seeyoga** [vkbottle/vkbottle#135]
**Опишите баг**
При попадание в росток, получаю ошибку  
``` cmd
[======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)VKBottle
] Using JSON_MODULE - json [TIME 16:06:48]
[VKBottle] Using asyncio loop - asyncio.windows_events [TIME 16:06:48]
[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "calback.py", line 28, in wrapper
    await bot.branch.add(ans.peer_id, "my_branch")
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\branch\database_branch.py", line 99, in add
    await self.get_branch(branch, context).enter()
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\branch\database_branch.py", line 36, in get_branch
    branch = bare()
TypeError: 'coroutine' object is not callable
```

**Что должно было случится**
Я подозреваю что должен быть цикл бесконечный где при наступление события он выходит, но после того как попадаешь в росток выпадает ошибка и бот не реагирует

**Ваш код**
``` python
@bot.on.message(text="хочу в бранч", lower=True)
async def wrapper(ans: Message):
    await ans("Теперь ты в бранче!")
    await bot.branch.add(ans.peer_id, "my_branch")


@bot.branch.simple_branch("my_branch")
async def branch(ans: Message):
    if ans.text.lower() == "выйти":
        await ans("Окей, вывожу!")
        await bot.branch.exit(ans.peer_id)

    await ans("Ты в бранче. Пиши «выйти», чтобы выйти отсюда.")
```

**Заполните поля:**
 - OS: Windows 10
 - Version of vkbottle: 2.7.5

**Дополнительная информация**
...

**Comment by quick-wq** [comment]
Залейте код на pastebin. Без отступов он нечитабелен, от слова совсем

**Comment by seeyoga** [comment]
> Залейте код на pastebin. Без отступов он нечитабелен

https://pastebin.com/nwt0CSjm

**Comment by markelovstyle** [comment]
Обновите VKBottle с master`a:

`pip install https://github.com/timoniq/vkbottle/archive/master.zip --upgrade`

**Comment by seeyoga** [comment]
> Обновите VKBottle с master`a:
> 
> `pip install https://github.com/timoniq/vkbottle/archive/master.zip --upgrade`

Помогло отлично)
