### ISSUE TITLE
Баг ошибка при работе branch (веток)

### ISSUE THREAD

**Issue by seeyoga** [vkbottle/vkbottle#136]
**Опишите баг**
После того как поподаешь в branch, выдает ошибку
```
`[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "calback.py", line 28, in wrapper
    await bot.branch.add(ans.peer_id, "my_branch", mark=mark)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\branch\database_branch.py", line 99, in add
    await self.get_branch(branch, context).enter()
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\branch\database_branch.py", line 36, in get_branch
    branch = bare()
TypeError: 'coroutine' object is not callable`

```
**Что должно было случится**
не должно быть ошибки, работа бота должна продолжаться 

**Ваш код**
https://pastebin.com/ewDxEP2m
``` python
@bot.on.message(text="ставлю боту <mark:int>", lower=True)
async def wrapper(ans: Message, mark):
    await ans("Теперь расскажи, что ты думаешь о нем:")
    await bot.branch.add(ans.peer_id, "my_branch", mark=mark)
 
@bot.branch.simple_branch("my_branch")
async def branch(ans: Message, mark):
    if ans.text.lower() in ["это все", "да"]:
        await ans(f"Окей, твоя оценка «{mark}» и рассказ о боте заcчитан!")
        await bot.branch.exit(ans.peer_id)
 
    await ans(f"Ты считаешь, что {ans.text}. Мы тебя поняли. Это все?")
```

**Заполните поля:**
 - OS: Windows 10 x64
 - Version of vkbottle: 2.7.5

**Дополнительная информация**
...

**Comment by quick-wq** [comment]
Удалите предыдущий issue или этот. Следуйте просьбам пожалуйста, тоже самое вас попросит timoniq

**Comment by seeyoga** [comment]
Так проблемы разные в этих двух issue? Просто описывать две разные проблемы в одном issue , не лучший выход.

**Comment by markelovstyle** [comment]
> Так проблемы разные в этих двух issue? Просто описывать две разные проблемы в одном issue , не лучший выход.

В смысле разные? Ты открыл 2 issue для одной и той же проблемы. Закрывай
