### ISSUE TITLE
Баг с клавиатурой (Location)

### ISSUE THREAD

**Issue by seeyoga** [vkbottle/vkbottle#138]
**Опишите баг**
При использование Location  в клавиатуре выдает ошибку 911 (возможно из за того что передается label по дефолту)

```
[VKBottle] Using JSON_MODULE - json======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
[TIME 01:06:03]
[VKBottle] Using asyncio loop - asyncio.windows_events [TIME 01:06:03]
[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "calback.py", line 28, in wrapper
    await ans('Хай, студент, рад тебя видеть сегодня!', keyboard = keyboard_gen(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\message.py", line 92, in __call__
    _mid = await self.api.messages.send(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\methods\messages.py", line 1107, in __call__
    return await self.request(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\request.py", line 26, in __call__
    response = await request(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\util\requester.py", line 68, in request
    return await error_handler.handle_error(exception)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 28, in handle_error
    return await self.unhandled_error(e)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 58, in unhandled_error
    raise e
vkbottle.utils.exceptions.VKError: (911, 'Keyboard format is invalid: button [1][0] action contains unknown fields', <Method MessagesSend>, {'random_id': 1201898978, 'peer_id': 30893183, 'message': 'Хай, студент, рад тебя видеть сегодня!', 'keyboard': '{"one_time": false, "buttons": [[{"action": {"type": "text", "label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #1"}, "color": "positive"}, {"action": {"type": "text", "label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #2"}, "color": "default"}], [{"action": {"type": "location", "label": "\\u0414\\u0435\\u0430\\u043d\\u043e\\u043d \\u0431\\u0435\\u0441\\u043f\\u043b\\u0430\\u0442\\u043d\\u043e"}}]], "inline": false}'}) 
```

**Что должно было случится**
Клавиатура должна отправляться корректно

**Ваш код**
``` python
@bot.on.message(text="привет", lower=True)
async def wrapper(ans: Message):
     await ans('Хай, студент, рад тебя видеть сегодня!', keyboard = keyboard_gen(
    [
        [{"text": "Кнопка #1", "color": "positive"}, {"text": "Кнопка #2"}], # Это первый ряд кнопок
        [{"type": "location", "text": "Деанон бесплатно"}], # Это второй ряд
    ]
))

```

**Заполните поля:**
 - OS: Windows 10 x64
 - Version of vkbottle: 2.7.5

**Дополнительная информация***
Если отправлять клавиатуру без поля text, то присвоится пустой label

**Comment by timoniq** [comment]
Скорее всего в кнопке с типом `location` текст передается через поле `label`

**Comment by seeyoga** [comment]
Попробывал с label, так же получил ошибку 
```
[VKBottle======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)] Using JSON_MODULE - json
 [TIME 12:06:48]
[VKBottle] Using asyncio loop - asyncio.windows_events [TIME 12:06:48]
[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "calback.py", line 29, in wrapper
    await ans('Хай, студент, рад тебя видеть сегодня!',keyboard=keyboard_gen(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\message.py", line 92, in __call__
    _mid = await self.api.messages.send(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\methods\messages.py", line 1107, in __call__
    return await self.request(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\request.py", line 26, in __call__
    response = await request(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\util\requester.py", line 68, in request
    return await error_handler.handle_error(exception)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 28, in handle_error
    return await self.unhandled_error(e)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 58, in unhandled_error
    raise e
vkbottle.utils.exceptions.VKError: (911, 'Keyboard format is invalid: button [1][0] action contains unknown fields', <Method MessagesSend>, {'random_id': -193521773, 'peer_id': 30893183, 'message': 'Хай, студент, рад тебя видеть сегодня!', 'keyboard': '{"one_time": false, "buttons": [[{"action": {"type": "text", "label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #1"}, "color": "positive"}, {"action": {"type": "text", "label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #2"}, "color": "default"}], [{"action": {"type": "location", "label": "\\u0414\\u0435\\u0430\\u043d\\u043e\\u043d \\u0431\\u0435\\u0441\\u043f\\u043b\\u0430\\u0442\\u043d\\u043e"}}]], "inline": false}'})
```

***Мой код***
``` python
@bot.on.message(text="привет", lower=True)
async def wrapper(ans: Message):
     await ans('Хай, студент, рад тебя видеть сегодня!',keyboard=keyboard_gen(
    [
        [{"text": "Кнопка #1", "color": "positive"}, {"text": "Кнопка #2"}], # Это первый ряд кнопок
        [{"type": "location", "label": "Деанон бесплатно"}], # Это второй ряд
    ])
    )
```

**Comment by timoniq** [comment]
В кнопке для отправки местоположения нельзя поставить свой текст

Из документации вк:

<img width="663" alt="Screen Shot 2020-06-21 at 19 41 56" src="https://user-images.githubusercontent.com/52574917/85230207-530ee300-b3f7-11ea-9e7b-21537823f1be.png">

**Comment by seeyoga** [comment]
> В кнопке для отправки местоположения нельзя поставить свой текст
> 
> Из документации вк:
> 
> <img alt="Screen Shot 2020-06-21 at 19 41 56" width="663" src="https://user-images.githubusercontent.com/52574917/85230207-530ee300-b3f7-11ea-9e7b-21537823f1be.png">

Так по чему нельзя отправить кнопку без label? Он автоматом подставляется где то?

*** Ошибка *** 

``` cmd
[VKBottle] Using JSON_MODULE - json [TIME 20:06:19]
[VKBottle] Using asyncio loop - asyncio.windows_events [TIME 20:06:19]
[VKBottle] Receiving updates from conversations [TIME 20:06:19]
[VKBottle] Conversation count - 1 [TIME 20:06:19]
[VKBottle] Answering... [TIME 20:06:19]
[VKBottle] Polling successfully started. Press Ctrl+C to stop it [TIME 20:06:19]
[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "d:/vk-bot-qwest/longpool.py", line 22, in wrapper
    await ans('Хай, студент, рад тебя видеть сегодня!',keyboard=keyboard_gen(
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\message.py", line 92, in __call__
    _mid = await self.api.messages.send(
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\methods\messages.py", line 1107, in __call__
    return await self.request(
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\request.py", line 26, in __call__
    response = await request(
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\util\requester.py", line 68, in request
    return await error_handler.handle_error(exception)
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 28, in handle_error
    return await self.unhandled_error(e)
  File "d:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 58, in unhandled_error
    raise e
vkbottle.utils.exceptions.VKError: (911, 'Keyboard format is invalid: button [1][0] action contains unknown fields', <Method MessagesSend>, {'random_id': -930423791, 'peer_id': 30893183, 'message': 'Хай, студент, рад тебя видеть сегодня!', 'keyboard': '{"one_time": false, "buttons": [[{"action": {"type": "text", "label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #1"}, "color": "positive"}, {"action": {"type": "text", "label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #2"}, "color": "default"}], [{"action": {"type": "location", "label": null}}]], "inline": false}'}) 
```

*** Мой код ***
``` python
@bot.on.message(text="привет", lower=True)
async def wrapper(ans: Message):
     await ans('Хай, студент, рад тебя видеть сегодня!',keyboard=keyboard_gen(
    [
        [{"text": "Кнопка #1", "color": "positive"}, {"text": "Кнопка #2"}], # Это первый ряд кнопок
        [{"type": "location"}], # Это второй ряд
    ])
    )
```

У меня есть догадка что в этом месте подставляеться label ко всем кнопкам, потому что если закомментировать строчку label не будет подставляться в кнопки, если ошибся и мои догадки не корректны, прошу помочь разобраться с этой проблемой


``` python
 rows = pattern
    buttons = list()
    for row in rows:
        row_buttons = list()
        for button in row:
            row_buttons.append(
                dict(
                    action=dict(
                        type=button.get("type", "text"),
                        label=button.get("text", button.get("label")), # часть которая подставляет label к кнопкам
                        **{
                            k: v
                            for k, v in button.items()
                            if k not in ["type", "text", "label", "color"]
                        }
                    ),
                    **(
                        {"color": button.get("color", "default")}
                        if button.get("type", "text") == "text"
                        else {}
                    )
                )
            )
        buttons.append(row_buttons)

    keyboard = str(
        json.dumps(dict(one_time=one_time, buttons=buttons, inline=inline))
        .encode("utf-8")
        .decode("utf-8")
    )
```

**Comment by seeyoga** [comment]
@timoniq, хотел бы уточнить будит ли решаться данный вопрос?

**Comment by timoniq** [comment]
@seeyoga, Извините, не видел ваш ответ, если вы поняли в чем проблема вы можете сделать пул реквест с ее решением, или я решу сам чуть позже
Если ситуация срочная можете воспользоваться генератором Keyboard

**Comment by timoniq** [comment]
Все, исправил. Извините за долгое ожидание

**Comment by seeyoga** [comment]
Первый вариант генерации клавиатуры работает. Спасибо большое @timoniq  за быструю помощь. Ошибка сохраняется если использовать второй вариант. 

***Мой код***

**Код клавиатуры**
```python
keyboard = Keyboard(inline=True)
keyboard.add_row()
keyboard.add_button(Text("Кнопка #1"), color="positive")
keyboard.add_button(Text("Кнопка #2"))
keyboard.add_row()
keyboard.add_button(Location())
```

**Код отправки клавиатуры**
```python
@bot.on.message(text="привет", lower=True)
async def wrapper(ans: Message):
     await ans('Хай, студент, рад тебя видеть сегодня!',keyboard=keyboard.generate())
```

**Ошибка**
```cmd
[VKBottle] Using JSON_MODULE - json [TIME 10:06:59]
[VKBottle] Using asyncio loop - asyncio.windows_events [TIME 10:06:59]
[VKBottle] Receiving updates from conversations [TIME 10:06:59]
[VKBottle] Conversation count - 1 [TIME 10:06:59]
[VKBottle] Answering... [TIME 10:06:59]
[VKBottle] While parent_processor was handling error occurred 

Traceback (most recent call last):
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\framework\swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\framework\bot\processor.py", line 81, in message_processor
    task = await rules[0].call(*args, **kwargs)
  File "longpool.py", line 24, in wrapper
    await ans('Хай, студент, рад тебя видеть сегодня!',keyboard=keyboard.generate())
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\message.py", line 92, in __call__
    _mid = await self.api.messages.send(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\types\methods\messages.py", line 1107, in __call__
    return await self.request(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\request.py", line 26, in __call__
    response = await request(
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\util\requester.py", line 68, in request
    return await error_handler.handle_error(exception)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 28, in handle_error
    return await self.unhandled_error(e)
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\api\error_handler\error_handler.py", line 58, in unhandled_error
    raise e
vkbottle.utils.exceptions.VKError: (911, 'Keyboard format is invalid: button [1][0] has invalid type', <Method MessagesSend>, {'random_id': 1194720904, 'peer_id': 30893183, 'message': 'Хай, студент, рад тебя видеть сегодня!', 'keyboard': '{"one_time": false, "inline": true, "buttons": [[{"action": {"label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #1", "type": "text"}, "color": "positive"}, {"action": {"label": "\\u041a\\u043d\\u043e\\u043f\\u043a\\u0430 #2", "type": "text"}, "color": "default"}], [{"action": {}}]]}'})
```
Если оставим ковычкни  получим исключение что к Location нельзя назначить метку
```cmd
Traceback (most recent call last):
  File "longpool.py", line 6, in <module>
    from keyboards import keyboard
  File "D:\vk-bot-qwest\keyboards.py", line 10, in <module>
    keyboard.add_button(Location(""))
  File "D:\vk-bot-qwest\env\lib\site-packages\vkbottle\api\keyboard\action.py", line 17, in __init__
    raise KeyboardError(
vkbottle.utils.exceptions.KeyboardError: Action Location cannot assign label
```
Есть предположение что label к кнопки подставляеться в этой части кода, но как именно еще не понял
```python
class Action:
    def __init__(
        cls,
        label: str = None,
        payload: str = None,
        link: str = None,
        hash: str = None,
        app_id: int = None,
        owner_id: int = None,
    ):
        for k, v in except_none_self(locals()).items():
            if not hasattr(cls, k):
                raise KeyboardError(
                    "Action {} cannot assign {}".format(cls.__class__.__name__, k)
                )
            setattr(cls, k, v)
            cls.type = getattr(cls, "type")

    def dict(self):
        return vars(self)

    def __repr__(self):
        return f"<Keyboard (action) {self.__class__.__qualname__}>"
```
