### ISSUE TITLE
Баг [VKBottle] While parent_processor was handling error occurred 

### ISSUE THREAD

**Issue by Doncode** [vkbottle/vkbottle#160]
**Опишите баг**
```
[VKBottle] While parent_processor was handling error occurred 
Traceback (most recent call last):
  File "/vkbottle/vkbottle/framework/framework/swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "/vkbottle/vkbottle/framework/bot/processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "/vkbottle/vkbottle/framework/bot/processor.py", line 44, in message_processor
    client_info=client_info,
  File "pydantic/main.py", line 338, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Message
client_info -> button_actions -> 6
  value is not a valid enumeration member; permitted: 'text', 'location', 'vkpay', 'open_app', 'open_link', 'open_photo' (type=type_error.enum; enum_values=[<ButtonActions.text: 'text'>, <ButtonActions.location: 'location'>, <ButtonActions.vkpay: 'vkpay'>, <ButtonActions.open_app: 'open_app'>, <ButtonActions.open_link: 'open_link'>, <ButtonActions.open_photo: 'open_photo'>])
 [TIME 14:07:33]
```

Возникает ошибка. Процесс продолжает работать, но бот перестает обрабатывать новые сообщения после этой ошибки

**Comment by Doncode** [comment]
Проблема решилась добавлением в Enum дополнительного свойства callback
pull request https://github.com/timoniq/vkbottle/pull/161
