### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by LooPeKa** [vkbottle/vkbottle#163]
**Опишите баг**
```
[VKBottle] While parent_processor was handling error occurred

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/vkbottle/framework/framework/swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/vkbottle/framework/bot/processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/vkbottle/framework/bot/processor.py", line 42, in message_processor
    message = Message(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pydantic/main.py", line 338, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Message
client_info -> button_actions -> 6
  value is not a valid enumeration member; permitted: 'text', 'location', 'vkpay', 'open_app', 'open_link', 'open_photo' (type=type_error.enum; enum_values=[<ButtonActions.text: 'text'>, <ButtonActions.location: 'location'>, <ButtonActions.vkpay: 'vkpay'>, <ButtonActions.open_app: 'open_app'>, <ButtonActions.open_link: 'open_link'>, <ButtonActions.open_photo: 'open_photo'>])
```

**Что должно было случится**
Бот отвечает ответом от messages.getById()

**Ваш код**
[Код](https://pastebin.com/7NE9mvN3)

**Заполните поля:**
 - OS: Android
 - Version of vkbottle: 2.7.4```

**Дополнительная информация**
Запускаю через Termux, но на Pydroid та же история

**Comment by timoniq** [comment]
> * Version of vkbottle: 2.7.4

Попробуй обновится с мастера

**Comment by LooPeKa** [comment]
> > * Version of vkbottle: 2.7.4
> 
> Попробуй обновится с мастера

Спасибо!)

**Comment by quick-wq** [comment]
@LooPeKa не используйте vk_api, пожалуйста
В документации **vkbottle** показано, как использовать методы VK API. Это будет лучше, чем использовать не асинхронную библиотеку.
