### ISSUE TITLE
Баг с клавиатурой

### ISSUE THREAD

**Issue by dadyarri** [vkbottle/vkbottle#171]
**Опишите баг**
При попытке нажать любую кнопку клавиатуры из Sova V RE 0.7d (или мобильной версии сайта, firefox on android) возникает ошибка 
```python
Traceback (most recent call last):
  File "/home/dadyarri/.local/share/virtualenvs/jacob-45jkGjGA/lib/python3.8/site-packages/vkbottle/framework/framework/swear_handler.py", line 26, in wrapper
    return await func(*args, **kwargs)
  File "/home/dadyarri/.local/share/virtualenvs/jacob-45jkGjGA/lib/python3.8/site-packages/vkbottle/framework/bot/processor.py", line 35, in parent_processor
    return await self.message_processor(obj, client_info)
  File "/home/dadyarri/.local/share/virtualenvs/jacob-45jkGjGA/lib/python3.8/site-packages/vkbottle/framework/bot/processor.py", line 42, in message_processor
    message = Message(
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Message
client_info -> button_actions -> 6
  value is not a valid enumeration member; permitted: 'text', 'location', 'vkpay', 'open_app', 'open_link', 'open_photo' (type=type_error.enum; enum_values=[<ButtonActions.text: 'text'>, <ButtonActions.location: 'location'>, <ButtonActions.vkpay: 'vkpay'>, <ButtonActions.open_app: 'open_app'>, <ButtonActions.open_link: 'open_link'>, <ButtonActions.open_photo: 'open_photo'>])
 [TIME 16:07:27]
```
и действие назначенное на эту кнопку не происходит

**Что должно было случит*ь*ся**
С десктопной версии сайта все работает как должно

**Ваш код**
Пример клавиатуры, не работает любая другая
```python
kb = Keyboard()
kb.add_row()
kb.add_button(
    Text(label="👉🏻 Пропустить", payload={"button": "skip_call_message"})
)
kb.add_button(Text(label="🚫 Отмена", payload={"button": "cancel_call"}))
return kb.generate()
```

**Заполните поля:**
 - OS: Manjaro Linux
 - Version of vkbottle: 2.7.6

**Comment by ghost** [comment]
Обновите VKBottle с мастера.

**Comment by dadyarri** [comment]
Благодарю
