### ISSUE TITLE
Ошибка  'NoneType' object has no attribute 'dict' при вызове update.object.message.dict()

### ISSUE THREAD

**Issue by ne-skazhu** [vkbottle/vkbottle#265]
https://github.com/timoniq/vkbottle/blob/05fd1173da756c971bfbcd7227aaf7fbe34a92df/vkbottle/tools/dev_tools/mini_types/bot/message.py#L56

Привет! Только начал изучать твоего бота, при стандартном запуске из readme после отправки в группу нового сообщения в консоли появляется ошибка 
2020-11-29 14:19:29.254 | ERROR    | vkbottle.exception_factory.error_handler.error_handler:handle:72 - 
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Roaming\Python\Python39\site-packages\vkbottle\dispatch\bot_router.py", line 19, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "C:\Users\Adam\AppData\Roaming\Python\Python39\site-packages\vkbottle\dispatch\views\bot\message.py", line 33, in handle_event
    message = message_min(event, ctx_api)
  File "C:\Users\Adam\AppData\Roaming\Python\Python39\site-packages\vkbottle\tools\dev_tools\mini_types\bot\message.py", line 55, in message_min
    **update.object.message.dict(),
AttributeError: 'NoneType' object has no attribute 'dict'

Пока только разбираюсь, но всё делал по инструкциям по установке. Что-то не то с установкой?

**Comment by Ne0shka** [comment]
Используйте версию Python ниже 3.9

**Comment by timoniq** [comment]
Какая версия api стоит в настройках группы?

**Comment by ne-skazhu** [comment]
Нашел проблему, в настройках группы стояла версия api 100, а у вас 103. Прошу прощения за беспокойство)
