### ISSUE TITLE
Баг: DocMessagesUploader - VKAPIError [100]

### ISSUE THREAD

**Issue by Timtaran** [vkbottle/vkbottle#306]
**Ожидаемое поведение:** 
отправка файла администратору

**Фактическое поведение:**
abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: peer_id is required for community messages

**Ваш код (опционально)**: ...
`await message.answer(attachment=await doc_uploader.upload(path_like='db.txt', title='Ну типо база данных', peer_id=549204433))`

**Заполните поля технической информации:**

---
vkbottle: v3-uploaders
vkbottle-types: 0.1.22
OS: Windows 7

---

**Comment by timoniq** [comment]
`answer` не принимает `peer_id`, для отправки сообщения человеку который никак не относится к ивенту есть `api.messages.send`

**Comment by Timtaran** [comment]
> `answer` не принимает `peer_id`, для отправки сообщения человеку который никак не относится к ивенту есть `api.messages.send`

но ведь ошибка связана с аплоадером...

**Comment by Timtaran** [comment]
Для тех, кто напишет что ошибка не в аплоадере:
Измененный код:

document = await doc_uploader.upload(path_like='db.txt', title='Ну типо база данных', peer_id=549204433)
await message.ctx_api.messages.send(peer_id=549204433, random_id=0, attachment=document)
Ошибка:
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\dispatch\bot_router.py", line 20, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\dispatch\views\bot\message.py", line 60, in handle_event
    handler_response = await handler.handle(message, **context_variables)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\dispatch\handlers\from_func_handler.py", line 26, in handle
    return await self.handler(event, **context)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\src\vk\blueprints\other.py", line 16, in keyboard
    document = await doc_uploader.upload(path_like='db.txt', title='Ну типо база данных', peer_id=549204433)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\tools\dev_tools\uploader\doc.py", line 14, in upload
    server = await self.get_server()
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\tools\dev_tools\uploader\doc.py", line 45, in get_server
    return (await self.api.request("docs.getMessagesUploadServer", kwargs))["response"]
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\api\api.py", line 53, in request
    return await self.validate_response(method, data, response)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\api\api.py", line 78, in validate_response
    response = await validator.validate(method, data, response, self)
  File "C:\Users\user\Documents\GitHub\pythonProject\LifeSimulator\venv\lib\site-packages\vkbottle\api\response_validator\vk_api_error_validator.py", line 31, in validate
    raise VKAPIError(code, msg)
abc.CodeErrorFactory_100: [100] One of the parameters specified was missing or invalid: peer_id is required for community messages
```

**Comment by timoniq** [comment]
нужно было сразу кидать полный трейс, из первоначально описанного поведения не ясно в каком месте возникает ошибка

**Comment by timoniq** [comment]
у вас стоит старая версия, это уже фиксилось вот здесь - [387e388](https://github.com/timoniq/vkbottle/pull/255/commits/387e388611f63a487cd05a06396c2b34eeb3919c)
