### ISSUE TITLE
Вопрос: Как ловить события от callback-кнопок?

### ISSUE THREAD

**Issue by dadyarri** [vkbottle/vkbottle#373]
Знаю про существование `bot.on.raw_event`, но при его использовании в рулзы и хендлеры приходит словарь. Как удобно обработать `MessageEvent`?

Так же, при добавлении rules/custom_rules к хендлеру `on.raw_event` появляется ошибка

```python
Traceback (most recent call last):
  File "/home/dadyarri/projects/uni-jacob/jacob-new/jacob/main.py", line 17, in <module>
    for bp in load_blueprints_from_package("jacob/blueprints"):
  File "/home/dadyarri/.cache/pypoetry/virtualenvs/jacob-8zWpfTeD-py3.9/lib/python3.9/site-packages/vkbottle/tools/dev_tools/utils.py", line 62, in load_blueprints_from_package
    bp_module = importlib.import_module(module_name + "." + module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/dadyarri/projects/uni-jacob/jacob-new/jacob/blueprints/registration.py", line 13, in <module>
    async def init_registration(message: Message):
  File "/home/dadyarri/.cache/pypoetry/virtualenvs/jacob-8zWpfTeD-py3.9/lib/python3.9/site-packages/vkbottle/framework/bot/labeler/default.py", line 194, in decorator
    *self.get_custom_rules(custom_rules),
  File "/home/dadyarri/.cache/pypoetry/virtualenvs/jacob-8zWpfTeD-py3.9/lib/python3.9/site-packages/vkbottle/framework/bot/labeler/default.py", line 208, in get_custom_rules
    return [self.custom_rules[k].with_config(self.rule_config)(v) for k, v in custom_rules.items()]  # type: ignore
  File "/home/dadyarri/.cache/pypoetry/virtualenvs/jacob-8zWpfTeD-py3.9/lib/python3.9/site-packages/vkbottle/framework/bot/labeler/default.py", line 208, in <listcomp>
    return [self.custom_rules[k].with_config(self.rule_config)(v) for k, v in custom_rules.items()]  # type: ignore
KeyError: 'custom_rules'
```

**Comment by timoniq** [comment]
1) если указать датакласс, приходить должен датакласс 
```python
@bot.on.raw_event(
    ..., 
    dataclass=MessageEvent
)
  ```
2) покажите как вы это делаете, так не очень понятно

**Comment by dadyarri** [comment]
1. Сейчас проверю *UPD:* Да, так все отлично работает
2.  Так не работает:
```python
@bp.on.raw_event(
    GroupEventType.MESSAGE_EVENT,
    dataclass=MessageEvent,
    custom_rules=PayloadContainsRule({"action": "init"}),
)
```
Но почему-то так - работает:
```python
@bp.on.raw_event(
    GroupEventType.MESSAGE_EVENT,
    MessageEvent,
    PayloadContainsRule({"action": "init"}),
)
```

3. Есть способ вызывать `messages.send_message_event_answer`/`messages.send` не обращаясь к ctx_api чтобы все параметры запроса подхватывались автоматически?
4. Не хватает конструктора event_data, чтобы в коде не лежал сырой json:
```python
    await message.ctx_api.messages.send_message_event_answer(
        event_id=message.object.event_id,
        peer_id=message.object.peer_id,
        user_id=message.object.user_id,
        event_data='{"type": "show_snackbar", "text": "Работает!"}',
    )
```

**Comment by timoniq** [comment]
1) :)
2) 
> ```python
> @bp.on.raw_event(
>     GroupEventType.MESSAGE_EVENT,
>     custom_rules=PayloadContainsRule({"action": "init"}),
> )
> ```

не представляю, где вы нашли такое. правила передаются в декоратор обычными поз. аргументами

```python
@bp.on.raw_event(
    GroupEventType.MESSAGE_EVENT,
    PayloadContainsRule({"action": "init"}),
    dataclass=MessageEvent
)
```

сразу напомню, что raw_event работает так, что регистрирует только один хендлер на один тип ивента (это поведение будет изменено в 3.1), поэтому если вы хотите делать обработку одного ивента множеством хендлеров, можно написать свой view для ивента или обрабатывать все в одном хендлере

3) для MessageEvent пока не добавлено никаких шорткатов (скорее всего появятся в новой версии типов)

4) для такого лучше оформить enhancement issue

**Comment by dadyarri** [comment]
Понял, спасибо
