### ISSUE TITLE
Баг: {краткое описание}

### ISSUE THREAD

**Issue by beliboba** [vkbottle/vkbottle#511]
Баг такой очень стрёмный
`Traceback (most recent call last):
  File "C:\Users\Beliboba\PycharmProjects\test228\slavebot1.py", line 1, in <module>
    from vkbottle.bot import Bot, Message
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\__init__.py", line 45, in <module>
    from .framework import (
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\framework\__init__.py", line 3, in <module>
    from .bot import Bot, BotBlueprint, run_multibot
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\framework\bot\__init__.py", line 1, in <module>
    from .blueprint import BotBlueprint
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\framework\bot\blueprint.py", line 5, in <module>
    from vkbottle.framework.bot.bot import Bot
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\framework\bot\bot.py", line 13, in <module>
    from vkbottle.api.vk_api.vk_api import VkApiGroup
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\vk_api\__init__.py", line 10, in <module>
    from .requests_pool import VkRequestsPool, vk_request_one_param_pool
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\vk_api\requests_pool.py", line 12, in <module>
    from .execute import VkFunction
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\vk_api\execute.py", line 10, in <module>
    from .vk_api import VkApi, VkApiMethod
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python310\lib\site-packages\vkbottle\api\vk_api\vk_api.py", line 19, in <module>
    import jconfig
ModuleNotFoundError: No module named 'jconfig'
`

**Comment by buvanenko** [comment]
pip install Jconfig

**Comment by beliboba** [comment]
Не помогает, кэп 😥

**Comment by ZeN220** [comment]
Откуда у тебя директория vkbottle/api/vk_api?

**Comment by axd1x8a** [comment]
Несмешно.

**Comment by beliboba** [comment]
Леее, а как починить-то?

**Comment by beliboba** [comment]
![image](https://user-images.githubusercontent.com/73661136/170344770-19ff5052-f093-4436-a573-814f36447e2f.png)

**Comment by axd1x8a** [comment]
Ещё одно такое ишью и вам навсегда будет заблокирован доступ к репозиторию.

Если вам нравится позориться, то делайте это в другом месте.

**Comment by beliboba** [comment]
Всмысле, чё за фигня?

**Comment by beliboba** [comment]
😡

**Comment by artegoser** [comment]
> Всмысле, чё за фигня?

Ахахахахахахахааххх

**Comment by beliboba** [comment]
вот смотрите что у меня в **venv** установлено
`$ pip list
Package            Version
------------------ -----------------
aiofiles           0.8.0
aiohttp            3.8.1
aiosignal          1.2.0
anyio              3.6.1
async-timeout      4.0.2
attrs              21.4.0
charset-normalizer 2.0.12
choicelib          0.1.5
frozenlist         1.3.0
idna               3.3
Jconfig            1.0
multidict          6.0.2
pip                21.3.1
pydantic           1.9.1
setuptools         60.2.0
sniffio            1.2.0
typing_extensions  4.2.0
vbml               1.1.post1
vkbottle           4.3.2
vkbottle-types     5.131.146.2.post1
watchgod           0.7
wheel              0.37.1
yarl               1.7.2
`
