### ISSUE TITLE
Баг: Exception при 'ответе' на сообщение.

### ISSUE THREAD

**Issue by Zensonaton** [vkbottle/vkbottle#516]
**Опишите баг**: При использовании User-Longpoll'а, если кто-то отправляет сообщение с ответом (reply, не пересылкой) и неважно, с какой именно стороны идёт пересылка; со стороны владельца страницы или нет, происходит Exception:
```python
'user_id'
Traceback (most recent call last):
  File ".../vkbottle/dispatch/base.py", line 22, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File ".../vkbottle/dispatch/views/abc/message.py", line 49, in handle_event
    message = await self.get_message(event, ctx_api, self.replace_mention)
  File ".../vkbottle/dispatch/views/user/message.py", line 28, in get_message
    return await message_min(event[1], ctx_api, replace_mention)
  File ".../vkbottle/tools/dev/mini_types/user/message.py", line 42, in message_min
    return MessageMin(
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1012, in pydantic.main.validate_model
  File ".../vkbottle/tools/dev/mini_types/user/message.py", line 29, in __foreign_messages
    foreign_message["user_id"] = values["user_id"]
KeyError: 'user_id'
```
![image](https://user-images.githubusercontent.com/66683075/170863812-23407d07-328d-4eec-870d-9dc13ce4da98.png)

**Ваш код (опционально)**: [pastebin](https://pastebin.com/gZ8vaUbP)

**Заполните поля технической информации:**

**vkbottle**: `4.3.2`
**vkbottle-types**: `5.131.146.2.post1`
**OS**: `Manjaro (Arch) Linux`

*оффтоп: а почему к issue assign'ится другой человек?*

**Comment by axd1x8a** [comment]
Fixed in 366d824234d91740e00cac0b01119c0fd298d919

**Comment by Zensonaton** [comment]
@FeeeeK, искринне извиняюсь, но даже после обновления всё равно создаётся Exception, но уже другой:
```python
1 validation error for MessageMin
reply_message
  Can't instantiate abstract class BaseForeignMessageMin with abstract method is_mentioned (type=type_error)
Traceback (most recent call last):
  File ".../vkbottle/dispatch/base.py", line 22, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File ".../vkbottle/dispatch/views/abc/message.py", line 49, in handle_event
    message = await self.get_message(event, ctx_api, self.replace_mention)
  File ".../vkbottle/dispatch/views/user/message.py", line 28, in get_message
    return await message_min(event[1], ctx_api, replace_mention)
  File ".../vkbottle/tools/dev/mini_types/user/message.py", line 42, in message_min
    return MessageMin(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MessageMin
reply_message
  Can't instantiate abstract class BaseForeignMessageMin with abstract method is_mentioned (type=type_error)
```

**Comment by axd1x8a** [comment]
:disappointed:
