### ISSUE TITLE
Баг: ValidationError при смене цветового оформления чата

### ISSUE THREAD

**Issue by TaurDev** [vkbottle/vkbottle#523]
При смене оформления чата пользователем вылетает ошибка о валидации

<details>
<summary>Сообщение ошибки</summary>

```
1 validation error for MessageNew
object -> message -> action -> type
  value is not a valid enumeration member; permitted: 'chat_photo_update', 'chat_photo_remove', 'chat_create', 'chat_title_update', 'chat_invite_user', 'chat_kick_user', 'chat_pin_message', 'chat_unpin_message', 'chat_invite_user_by_link', 'chat_invite_user_by_message_request', 'chat_screenshot' (type=type_error.enum; enum_values=[<MessagesMessageActionStatus.CHAT_PHOTO_UPDATE: 'chat_photo_update'>, <MessagesMessageActionStatus.CHAT_PHOTO_REMOVE: 'chat_photo_remove'>, <MessagesMessageActionStatus.CHAT_CREATE: 'chat_create'>, <MessagesMessageActionStatus.CHAT_TITLE_UPDATE: 'repl
1 validation error for MessageNew
object -> message -> action -> type
  value is not a valid enumeration member; permitted: 'chat_photo_update', 'chat_photo_remove', 'chat_create', 'chat_title_update', 'chat_invite_user', 'chat_kick_user', 'chat_pin_message', 'chat_unpin_message', 'chat_invite_user_by_link', 'chat_invite_user_by_message_request', 'chat_screenshot' (type=type_error.enum; enum_values=[<MessagesMessageActionStatus.CHAT_PHOTO_UPDATE: 'chat_photo_update'>, <MessagesMessageActionStatus.CHAT_PHOTO_REMOVE: 'chat_photo_remove'>, <MessagesMessageActionStatus.CHAT_CREATE: 'chat_create'>, <MessagesMessageActionStatus.CHAT_TITLE_UPDATE: 'chat_title_update'>, <MessagesMessageActionStatus.CHAT_INVITE_USER: 'chat_invite_user'>, <MessagesMessageActionStatus.CHAT_KICK_USER: 'chat_kick_user'>, <MessagesMessageActionStatus.CHAT_PIN_MESSAGE: 'chat_pin_message'>, <MessagesMessageActionStatus.CHAT_UNPIN_MESSAGE: 'chat_unpin_message'>, <MessagesMessageActionStatus.CHAT_INVITE_USER_BY_LINK: 'chat_invite_user_by_link'>, <MessagesMessageActionStatus.CHAT_INVITE_USER_BY_MESSAGE_REQUEST: 'chat_invite_user_by_message_request'>, <MessagesMessageActionStatus.CHAT_SCREENSHOT: 'chat_screenshot'>])
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\vkbottle\dispatch\base.py", line 22, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "C:\Python39\lib\site-packages\vkbottle\dispatch\views\abc\message.py", line 49, in handle_event
    message = await self.get_message(event, ctx_api, self.replace_mention)
  File "C:\Python39\lib\site-packages\vkbottle\dispatch\views\bot\message.py", line 28, in get_message
    return message_min(event, ctx_api, replace_mention)
  File "C:\Python39\lib\site-packages\vkbottle\tools\dev\mini_types\bot\message.py", line 85, in message_min
    update = MessageNew(**event)
  File "pydantic\main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MessageNew
object -> message -> action -> type
  value is not a valid enumeration member; permitted: 'chat_photo_update', 'chat_photo_remove', 'chat_create', 'chat_title_update', 'chat_invite_user', 'chat_kick_user', 'chat_pin_message', 'chat_unpin_message', 'chat_invite_user_by_link', 'chat_invite_user_by_message_request', 'chat_screenshot' (type=type_error.enum; enum_values=[<MessagesMessageActionStatus.CHAT_PHOTO_UPDATE: 'chat_photo_update'>, <MessagesMessageActionStatus.CHAT_PHOTO_REMOVE: 'chat_photo_remove'>, <MessagesMessageActionStatus.CHAT_CREATE: 'chat_create'>, <MessagesMessageActionStatus.CHAT_TITLE_UPDATE: 'chat_title_update'>, <MessagesMessageActionStatus.CHAT_INVITE_USER: 'chat_invite_user'>, <MessagesMessageActionStatus.CHAT_KICK_USER: 'chat_kick_user'>, <MessagesMessageActionStatus.CHAT_PIN_MESSAGE: 'chat_pin_message'>, <MessagesMessageActionStatus.CHAT_UNPIN_MESSAGE: 'chat_unpin_message'>, <MessagesMessageActionStatus.CHAT_INVITE_USER_BY_LINK: 'chat_invite_user_by_link'>, <MessagesMessageActionStatus.CHAT_INVITE_USER_BY_MESSAGE_REQUEST: 'chat_invite_user_by_message_request'>, <MessagesMessageActionStatus.CHAT_SCREENSHOT: 'chat_screenshot'>])
```

</details>

![image](https://user-images.githubusercontent.com/65149518/173064893-b5d224f6-a310-4d62-83cf-8410859f3f07.png)

**Comment by axd1x8a** [comment]
Покажите евент, который приходит.
