### ISSUE TITLE
AttributeError: type object 'KeyboardButton' has no attribute 'action

### ISSUE THREAD

**Issue by izya5346** [vkbottle/vkbottle#546]
Сделал по example.py
keyboard = Keyboard(one_time=True, inline=False).schema(
            [
            [
                {"label": "Button 1", "type": "text", "color": "positive"},
                {"label": "Button 2", "type": "text"},
            ],
            [{"label": "Button 3", "type": "text"}],
            ]
    ).get_json()
но возвращает ошибку

vkbottle==4.3.9
vkbottle-types==5.131.146.11
OS: Ubuntu LTS 22.04
python: 3.10.4

**Comment by axd1x8a** [comment]
Покажите трейс полностью

**Comment by izya5346** [comment]
> Покажите трейс полностью

ERROR:vkbottle:type object 'KeyboardButton' has no attribute 'action'
Traceback (most recent call last):
  File "/home/izyafroloff/foodcort/env/lib/python3.10/site-packages/vkbottle/dispatch/base.py", line 22, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "/home/izyafroloff/foodcort/env/lib/python3.10/site-packages/vkbottle/dispatch/views/abc/message.py", line 73, in handle_event
    handler_response = await handler.handle(message, **context_variables)
  File "/home/izyafroloff/foodcort/env/lib/python3.10/site-packages/vkbottle/dispatch/handlers/from_func_handler.py", line 32, in handle
    return await self.handler(event, **acceptable_context)
  File "/home/izyafroloff/foodcort/bot_vk/main.py", line 8, in echo
    keyboard = Keyboard(one_time=True, inline=False).schema(
  File "/home/izyafroloff/foodcort/env/lib/python3.10/site-packages/vkbottle/tools/dev/keyboard/keyboard.py", line 37, in schema
    self.buttons[-1].append(KeyboardButton.from_dict(button))
  File "/home/izyafroloff/foodcort/env/lib/python3.10/site-packages/vkbottle/tools/dev/keyboard/button.py", line 34, in from_dict
    return cls(cls.action, cls.color, keyboard_data)  # type: ignore
AttributeError: type object 'KeyboardButton' has no attribute 'action'
