### ISSUE TITLE
Шампунь

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#634]
Пытаюсь попробовать хостинг pythonanywhere, выдает такую ошибку при включении бота.

python 3.9
INFO:vkbottle:logging is used as the default logger, but we recommend using loguru. It may also become a required dependency in future releases.
INFO:vkbottle:Loop will be ran forever
DEBUG:asyncio:Using selector: EpollSelector
INFO:vkbottle:Starting polling for <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
DEBUG:vkbottle:Getting polling server...
DEBUG:vkbottle:API request was validated
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Bot.run_polling() done, defined at /home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/framework/bot/bot.py:77> exception=ClientConnectorError(ConnectionKey(ho
st='api.vk.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('87.240.137.206', 443)"))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('87.240.137.206', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/framework/bot/bot.py", line 81, in run_polling
    async for event in polling.listen():
  File "/home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/polling/bot_polling.py", line 57, in listen
    server = await self.get_server()
  File "/home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/polling/bot_polling.py", line 51, in get_server
    self.group_id = (await self.api.request("groups.getById", {}))["response"][0]["id"]
  File "/home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/api/api.py", line 72, in request
    response = await self.http_client.request_text(
  File "/home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/http/aiohttp.py", line 73, in request_text
    response = await self.request_raw(url, method, data, **kwargs)
  File "/home/der4ik0/.local/lib/python3.9/site-packages/vkbottle/http/aiohttp.py", line 50, in request_raw
    async with self.session.request(url=url, method=method, data=data, **kwargs) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.vk.com:443 ssl:default [Connect call failed ('87.240.137.206', 443)]

python3.8 ошибка, по факту они одинаковые

INFO:vkbottle:logging is used as the default logger, but we recommend using loguru. It may also become a required dependency in future releases.
INFO:vkbottle:Loop will be ran forever
DEBUG:asyncio:Using selector: EpollSelector
INFO:vkbottle:Starting polling for <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
DEBUG:vkbottle:Getting polling server...
DEBUG:vkbottle:API request was validated
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Bot.run_polling() done, defined at /home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/framework/bot/bot.py:77> exception=ClientConnectorError(ConnectionKey(ho
st='api.vk.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('87.240.137.207', 443)"))>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('87.240.137.207', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/framework/bot/bot.py", line 81, in run_polling
    async for event in polling.listen():
  File "/home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/polling/bot_polling.py", line 57, in listen
    server = await self.get_server()
  File "/home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/polling/bot_polling.py", line 51, in get_server
    self.group_id = (await self.api.request("groups.getById", {}))["response"][0]["id"]
  File "/home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/api/api.py", line 72, in request
    response = await self.http_client.request_text(
  File "/home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/http/aiohttp.py", line 73, in request_text
    response = await self.request_raw(url, method, data, **kwargs)
  File "/home/der4ik0/.local/lib/python3.8/site-packages/vkbottle/http/aiohttp.py", line 50, in request_raw
    async with self.session.request(url=url, method=method, data=data, **kwargs) as response:
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.vk.com:443 ssl:default [Connect call failed ('87.240.137.207', 443)]

На windows 10 как и на ubuntu все работает,
Тогда тут в чем дело?

**Comment by ghost** [comment]
проверил, так на всех версиях python

**Comment by axd1x8a** [comment]
У вас или вашего хостера проблемы с dns, это не касается фреймворка.

**Comment by FlameHaker** [comment]
У тебя проблемы с интернетом на самом хостинге. Только менять сам хостинг или добиваться ответа от тп

Фреймворк тут не причем.

**Comment by FalconSokol1** [comment]
> проверил, так на всех версиях python

Ты решил эту проблему?

**Comment by axd1x8a** [comment]
> > проверил, так на всех версиях python
> 
> Ты решил эту проблему?
> 

@FalconSokol1 Эту проблему невозможно решить, боты не работают на pythonanywhere.

**Comment by FalconSokol1** [comment]
У меня получилось, представляешь. Вот буквально минут 15 назад решил. В 14.00 по мск завтра я распишу что и как.

**Comment by FalconSokol1** [comment]
Вообщем, как я разрешил эту проблему:

import datetime
import sqlite3
import os
import time

from vkbottle import Keyboard, Text, KeyboardButtonColor, OpenLink, Location, EMPTY_KEYBOARD, VKAPIError, \
    GroupEventType, GroupTypes, user, Callback

from vkbottle.bot import Bot, Message
from vkbottle import API
from vkbottle.http import AiohttpClient
from aiohttp import ClientSession
from aiohttp_socks import ProxyConnector
from config import token



os.environ["TZ"] = "Europe/Moscow"
time.tzset()

connector = ProxyConnector.from_url("http://proxy.server:3128")
session = ClientSession(connector = connector)
proxy = AiohttpClient(session = session)
api = API(token=token, http_client = proxy)
bot = Bot(api = api)

Да, на бесплатном хостинге косячно он запускается. Допустим изменил код, а он выдает ошибку. Выходишь в корневую папку с файлом .py или через консоль запускаешься и всё норм.

**Comment by axd1x8a** [comment]
Достаточно было прикрепить ссылку на документацию.
https://help.pythonanywhere.com/pages/403ForbiddenError/
