### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mrtnvgr** [vkbottle/vkbottle#664]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/master.zip`) и проблема осталась

### Описание

Раз-два в день появляется вот эта ошибка. Как я понял, в traceback написано что она происходит где-то в самом vkbottle при запросе `messages.getById`.

### Логи

```shell
2023-03-11_01:51:39.10041 2023-03-11 08:51:39.097 | ERROR    | vkreborn.error_handler:undefined_handler:14 - Аргументы: {}
2023-03-11_01:51:45.34020 2023-03-11 08:51:45.286 | ERROR    | vkbottle.exception_factory.error_handler.error_handler:handle:48 - list index out of range
2023-03-11_01:51:45.34031 Traceback (most recent call last):
2023-03-11_01:51:45.34034
2023-03-11_01:51:45.34036   File "<frozen runpy>", line 198, in _run_module_as_main
2023-03-11_01:51:45.34038   File "<frozen runpy>", line 88, in _run_code
2023-03-11_01:51:45.34040
2023-03-11_01:51:45.34042   File "/home/user/vkreborn/vkreborn/__main__.py", line 35, in <module>
2023-03-11_01:51:45.34044     main()
2023-03-11_01:51:45.34046     └ <function main at 0x7fac3e00e700>
2023-03-11_01:51:45.34048
2023-03-11_01:51:45.34050   File "/home/user/vkreborn/vkreborn/__main__.py", line 31, in main
2023-03-11_01:51:45.34052     user.run_forever()
2023-03-11_01:51:45.34054     │    └ <function User.run_forever at 0x7fac3f125940>
2023-03-11_01:51:45.34056     └ <vkbottle.framework.user.user.User object at 0x7fac3feb8f90>
2023-03-11_01:51:45.34059
2023-03-11_01:51:45.34061   File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/framework/user/user.py", line 115, in run_forever
2023-03-11_01:51:45.34063     self.loop_wrapper.run_forever(self.loop)
2023-03-11_01:51:45.34072     │    │            │           │    └ <property object at 0x7fac3f2b3510>
2023-03-11_01:51:45.34076     │    │            │           └ <vkbottle.framework.user.user.User object at 0x7fac3feb8f90>
2023-03-11_01:51:45.34078     │    │            └ <function LoopWrapper.run_forever at 0x7fac3e99eb60>
2023-03-11_01:51:45.34084     │    └ <vkbottle.tools.dev.loop_wrapper.LoopWrapper object at 0x7fac41123b10>
2023-03-11_01:51:45.34086     └ <vkbottle.framework.user.user.User object at 0x7fac3feb8f90>
2023-03-11_01:51:45.34088   File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/tools/dev/loop_wrapper.py", line 50, in run_forever
2023-03-11_01:51:45.34090     loop.run_forever()
2023-03-11_01:51:45.34092     │    └ <function BaseEventLoop.run_forever at 0x7fac41d60ae0>
2023-03-11_01:51:45.34095     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
2023-03-11_01:51:45.34097   File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
2023-03-11_01:51:45.34099     self._run_once()
2023-03-11_01:51:45.34101     │    └ <function BaseEventLoop._run_once at 0x7fac41d628e0>
2023-03-11_01:51:45.34109     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
2023-03-11_01:51:45.34112   File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
2023-03-11_01:51:45.34114     handle._run()
2023-03-11_01:51:45.34116     │      └ <function Handle._run at 0x7fac422f4f40>
2023-03-11_01:51:45.34118     └ <Handle Task.task_wakeup(<Future finished result=None>)>
2023-03-11_01:51:45.34120   File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
2023-03-11_01:51:45.34125     self._context.run(self._callback, *self._args)
2023-03-11_01:51:45.34127     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
2023-03-11_01:51:45.34129     │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
2023-03-11_01:51:45.34131     │    │            │    └ <member '_callback' of 'Handle' objects>
2023-03-11_01:51:45.34137     └ <Handle Task.task_wakeup(<Future finished result=None>)>
2023-03-11_01:51:45.34140 > File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/dispatch/base.py", line 22, in route
2023-03-11_01:51:45.34142     await view.handle_event(event, ctx_api, self.state_dispenser)
2023-03-11_01:51:45.34144           │    │            │      │        │    └ <vkbottle.dispatch.dispenser.builtin.BuiltinStateDispenser object at 0x7fac3b3f2610>
2023-03-11_01:51:45.34146           │    │            │      │        └ <vkbottle.dispatch.base.Router object at 0x7fac3e64d750>
2023-03-11_01:51:45.34151           │    │            │      └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
2023-03-11_01:51:45.34153           │    │            └ [4, 1192656, 8227, 2000000088, 1678499656, '...', '%ролл', {'from': '355466183'}, 659377987]
2023-03-11_01:51:45.34156           │    └ <function ABCMessageView.handle_event at 0x7fac3e9527a0>
2023-03-11_01:51:45.34158           └ <UserMessageView handlers=[<FromFuncHandler invite_handler blocking=True rules=(<PeerRule>, <AliasRule>, <ModerRule>)>, <From...
2023-03-11_01:51:45.34160   File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/dispatch/views/abc/message.py", line 49, in handle_event
2023-03-11_01:51:45.34162     message = await self.get_message(event, ctx_api, self.replace_mention)
2023-03-11_01:51:45.34168                     │    │           │      │        │    └ False
2023-03-11_01:51:45.34171                     │    │           │      │        └ <UserMessageView handlers=[<FromFuncHandler invite_handler blocking=True rules=(<PeerRule>, <AliasRule>, <ModerRule>)>, <From...
2023-03-11_01:51:45.34176                     │    │           │      └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
2023-03-11_01:51:45.34179                     │    │           └ [4, 1192656, 8227, 2000000088, 1678499656, '...', '%ролл', {'from': '355466183'}, 659377987]
2023-03-11_01:51:45.34181                     │    └ <staticmethod(<function ABCUserMessageView.get_message at 0x7fac3f106d40>)>
2023-03-11_01:51:45.34183                     └ <UserMessageView handlers=[<FromFuncHandler invite_handler blocking=True rules=(<PeerRule>, <AliasRule>, <ModerRule>)>, <From...
2023-03-11_01:51:45.34185   File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/dispatch/views/user/message.py", line 29, in get_message
2023-03-11_01:51:45.34188     return await message_min(event[1], ctx_api, replace_mention)
2023-03-11_01:51:45.34190                  │           │         │        └ False
2023-03-11_01:51:45.34199                  │           │         └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
2023-03-11_01:51:45.34205                  │           └ [4, 1192656, 8227, 2000000088, 1678499656, '...', '%ролл', {'from': '355466183'}, 659377987]
2023-03-11_01:51:45.34207                  └ <function message_min at 0x7fac3e897ba0>
2023-03-11_01:51:45.34210   File "/root/.cache/pypoetry/virtualenvs/vkreborn-sBwWEimx-py3.11/lib/python3.11/site-packages/vkbottle/tools/dev/mini_types/user/message.py", line 41, in message_min
2023-03-11_01:51:45.34212     message_object = (await ctx_api.request("messages.getById", {"message_ids": message_id}))[
2023-03-11_01:51:45.34214                             │       │                                           └ 1192656
2023-03-11_01:51:45.34216                             │       └ <function API.request at 0x7fac3e922980>
2023-03-11_01:51:45.34218                             └ <API token_generator=<<class 'vkbottle.api.token_generator.single.SingleTokenGenerator'>>...>
2023-03-11_01:51:45.34221
2023-03-11_01:51:45.34223 IndexError: list index out of range
```

**Comment by axd1x8a** [comment]
Ошибка происходит из-за того, что ботл пытается получить сообщение, которое успели удалить. Советую использовать raw_event хендлеры, чтобы работать с евентом напрямую
