### ISSUE TITLE
Отрабатывает другой код, нежели ожидалось

### ISSUE THREAD

**Issue by Nikitonz** [vkbottle/vkbottle#833]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

В моём коде по нажатию на кнопку отсылается личное сообщение.
При открытии ветки личных сообщений с сообществом (куда и пришел ответ) выпадает следующая ошибка
```
Traceback (most recent call last):
  File "C:\Users\nikit\Desktop\AlfredRforVK.com\venv\Lib\site-packages\vkbottle\dispatch\base.py", line 20, in route
    if not await view.process_event(event):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\Desktop\AlfredRforVK.com\venv\Lib\site-packages\vkbottle\dispatch\views\bot\raw.py", line 40, in process_event
    return GroupEventType(self.get_event_type(event)) in self.handlers
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikit\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'message_read' is not a valid GroupEventType
```

При этом существует код только при обработки callback от кнопок.
В коде отсутствую какие-либо обработчики чтения сообщений
Обработчик нажатия кнопок выполнен в соответствии с образцом сайта документации

**Comment by GODIMONGO** [comment]
from vkbottle.bot import Bot, Message

bot = Bot(token='')
@bot.on.private_message()
async def test(message: Message):
    await message.answer('Привет' + str(message.text) )

bot.run_forever()

ERROR    | 2024-01-12 00:01:04 | vkbottle.exception_factory.error_handler.error_handler:handle:48 > 'message_read' is not a valid GroupEventType
Traceback (most recent call last):
  File "C:\Users\Дмитрий\PycharmProjects\vkbot\.venv\Lib\site-packages\vkbottle\dispatch\base.py", line 20, in route
    if not await view.process_event(event):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\PycharmProjects\vkbot\.venv\Lib\site-packages\vkbottle\dispatch\views\bot\raw.py", line 40, in process_event
    return GroupEventType(self.get_event_type(event)) in self.handlers
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Дмитрий\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'message_read' is not a valid GroupEventType

**Comment by fiersik** [comment]
@GODIMONGO Надо выключить евент message_read в настройках группы 

Так же нет смысла написания str(message.text) так как message.text уже str

**Comment by GODIMONGO** [comment]
Большое спасибо! Да я просто привык всегда указывать тип
