### ISSUE TITLE
template или keyboard

### ISSUE THREAD

**Issue by ciklopper** [vkbottle/vkbottle#855]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

Если в answer передать dict содержащий keyboard и template, то происходит следующая ошибка:
"vkbottle:One of the parameters specified was missing or invalid: Only template or keyboard field should be specified".
Но если передать параметр template и параметр keyboard отдельно то ошибки не будет. Важно, это верно, когда у keyboard inline = False.

Данная ошибка должна возникать, только когда одновременно передаётся template и Keyboard(inline=True)

### Пример кода

```python
#так получаем ошибку
await message.answer(**answer)

#так работает, если Keyboard(inline=False)
await message.answer('Приветствую тебя', keyboard=keyboard, template=template)
```

### Логи

```shell
ERROR:vkbottle:One of the parameters specified was missing or invalid: Only template or keyboard field should be specified
Traceback (most recent call last):
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/dispatch/base.py", line 22, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/dispatch/views/abc/message.py", line 73, in handle_event
    handler_response = await handler.handle(message, **context_variables)
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/dispatch/handlers/from_func_handler.py", line 32, in handle
    return await self.handler(event, **acceptable_context)
  File "/home/runner/ServerVK/main.py", line 32, in main_handler
    await message.answer(**answer)
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/tools/dev/mini_types/base/message.py", line 198, in answer
    response = (await self.ctx_api.messages.send(peer_ids=[self.peer_id], **data))[0]  # type: ignore
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle_types/methods/messages.py", line 206, in send
    response = await self.api.request("messages.send", params)
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/api/api.py", line 79, in request
    return await self.validate_response(method, data, response)  # type: ignore
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/api/api.py", line 103, in validate_response
    response = await validator.validate(method, data, response, self)  # type: ignore
  File "/home/runner/ServerVK/.pythonlibs/lib/python3.10/site-packages/vkbottle/api/response_validator/vk_api_error_validator.py", line 48, in validate
    raise VKAPIError[code](**error)
vkbottle.exception_factory.code_exception.VKAPIError_100: One of the parameters specified was missing or invalid: Only template or keyboard field should be specified
```

**Comment by axd1x8a** [comment]
Это ошибка от вк, фреймворк тут не при чем, смотрите в логах что передается в параметрах запроса.

**Comment by ciklopper** [comment]
> Это ошибка от вк, фреймворк тут не при чем, смотрите в логах что передается в параметрах запроса.

Не углубился в логи, отправил их чисто машинально. Очень странная история, что передав их не с помощью словаря, это работает.
Буду считать не багом, а найденной фичей.

В таком случае можно закрывать.
