### ISSUE TITLE
Ошибка Aiohttp

### ISSUE THREAD

**Issue by ghost** [vkbottle/vkbottle#893]
### Checklist

- [X] Я уверен, что это баг фреймворка
- [X] Я искал похожие баги в issues
- [X] Я установил последнюю версию (`pip3 install -U https://github.com/vkbottle/vkbottle/archive/dev.zip`) и проблема осталась

### Описание

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.vk.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate - с минимальным кодом выдает такую ошибку

### Пример кода

```python3
import asyncio
from vkbottle.bot import Bot, Message

bot = Bot("")



@bot.on.message()
async def handler(_) -> str:
    return "Hello world!"

bot.run_forever()
```

### Логи

Traceback (most recent call last):
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "C:\Program Files\Python311\Lib\asyncio\sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "C:\Program Files\Python311\Lib\asyncio\sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python311\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\vkbottle\framework\bot\bot.py", line 81, in run_polling
    async for event in polling.listen():
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\vkbottle\polling\bot_polling.py", line 57, in listen
    server = await self.get_server()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\vkbottle\polling\bot_polling.py", line 51, in get_server
    self.group_id = (await self.api.request("groups.getById", {}))["response"][0]["id"]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\vkbottle\api\api.py", line 72, in request
    response = await self.http_client.request_text(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\vkbottle\http\aiohttp.py", line 73, in request_text
    response = await self.request_raw(url, method, data, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\vkbottle\http\aiohttp.py", line 50, in request_raw
    async with self.session.request(url=url, method=method, data=data, **kwargs) as response:
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Der4ik0\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.vk.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')]
INFO     | 2024-02-17 14:28:29 | vkbottle.tools.dev.loop_wrapper:run_forever:52 > Keyboard Interrupt

**Comment by axd1x8a** [comment]
Проблема не относится к фреймворку, проверьте цепи сертификатов на вашей системе.
`openssl s_client -connect api.vk.com:443 -4 <<< "Q"`
